// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrvsNtiQ7Vv5Ph0FLkFJ88-KFEu0c3dxw',
    appId: '1:298832008266:web:a37c67793d4d83d36942b3',
    messagingSenderId: '298832008266',
    projectId: 'citiguide-c12b6',
    authDomain: 'citiguide-c12b6.firebaseapp.com',
    storageBucket: 'citiguide-c12b6.appspot.com',
    measurementId: 'G-R8HL08WZ1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmzB1qISkdWOJJqM2MbLxXLUUV-Gsg8yg',
    appId: '1:298832008266:android:e733aff52a6b01556942b3',
    messagingSenderId: '298832008266',
    projectId: 'citiguide-c12b6',
    storageBucket: 'citiguide-c12b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhywbXY9tCeyMA09m_7BT8dvpEU5D_LTk',
    appId: '1:298832008266:ios:e570c4c1537c91ed6942b3',
    messagingSenderId: '298832008266',
    projectId: 'citiguide-c12b6',
    storageBucket: 'citiguide-c12b6.appspot.com',
    iosBundleId: 'com.example.citiGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhywbXY9tCeyMA09m_7BT8dvpEU5D_LTk',
    appId: '1:298832008266:ios:cdf15423486f54186942b3',
    messagingSenderId: '298832008266',
    projectId: 'citiguide-c12b6',
    storageBucket: 'citiguide-c12b6.appspot.com',
    iosBundleId: 'com.example.citiGuide.RunnerTests',
  );
}
